services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8000"
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://${API_HOST}:${API_PORT}/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
